### PR TITLE
Fire events when breaking and placing blocks

### LINKED ISSUE #66: Able to get around FTB claims
**Describe the bug**
Exchange tool and destruction tool are able to get around protection claims on servers 

**To Reproduce**
Use tools in another players claim

### PR DESCRIPTION
**Pull request by jeremiahwinsley**
Fixes #66, #103

### CODE REVIEW

**Review by MichaelHillcox — CHANGES_REQUESTED** [review]
This looks to only address the building gadget and not the other gadgets building / exchanging / removal methods

**Comment by jeremiahwinsley** [comment]
Not sure which method I am missing - as far as I can tell, all 5 gadgets go through one of these 3 methods.

**Comment by MichaelHillcox** [comment]
I could be wrong, I'll take a look at the code properly and get back to you. I was meant to sort this months ago but it's been a while since I've had the time for BG

**Comment by Direwolf20-MC** [comment]
Thanks for this :) I wound up adding a similiar line to a few other places, and since I had already ported to 1.21 by the time I got to this I just added it myself. Thank you again!

**Pull request closed without merging**
