### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by Fiocher**

### CODE REVIEW

**Comment by Direwolf20-MC** [comment]
Thank you very much!!

**Comment by Direwolf20-MC** [comment]
Oh but I don't think you want it in the generated folder, as it'll get removed next time i run data -- please move it to the manual resources\assets\buildinggadgets2\lang

**Comment by Fiocher** [comment]
> Oh but I don't think you want it in the generated folder, as it'll get removed next time i run data -- please move it to the manual resources\assets\buildinggadgets2\lang

How to move it? This is my first PR and I'm not familiar with GitHub either.

**Comment by Direwolf20-MC** [comment]
I'll bring the PR in and move it for you :) thanks!

**Comment by Fiocher** [comment]
> I'll bring the PR in and move it for you :) thanks!

I updated it again, what should I do to prevent it from being removed?

**Comment by Direwolf20-MC** [comment]
Yup, if you 'pull' from my current branch, it'll move to the right place - just update it in place now. Thanks again for doing this :)

**Comment by Fiocher** [comment]
> Yup, if you 'pull' from my current branch, it'll move to the right place - just update it in place now. Thanks again for doing this :)

Do I need to create a new pr for every update?

**Comment by Direwolf20-MC** [comment]
Yes :) I believe you do.

**Pull request merged**
